#!/usr/bin/env ruby -n

ANSI_ESCAPE_SEQUENCE_REGEXP ||= /\e\[\d{0,2}m/

input = $_

process ||= false
process = true if input =~ /^#{ANSI_ESCAPE_SEQUENCE_REGEXP}?diff --git/

output = if process
  input
else
  input
end

print output
