export CLICOLOR="true"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

eval "$(rbenv init -)"

alias b="bundle"
alias be="bundle exec"
alias g="git"
alias h="heroku"
alias i="irb"
alias r="rails"
alias ra="rake"
alias rb="rbenv"
alias rsp="rspec"
alias ru="ruby"
